spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fiv5_db?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: Rlaxodn0819!

  jpa:
    hibernate:
      ddl-auto: update # (개발 시 update 또는 none)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties.hibernate.format_sql: true

apple:
  audience: com.teamfiv5.fiv5app
  iss: https://appleid.apple.com
  keys-url: https://appleid.apple.com/auth/keys

jwt:
  secret-key: uKa6]oJ^3K*0zQK.pF<1pmu.QfI7By)j[.Wl8?QJmAZ
  access-token-validity-seconds: 3600